apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: droid-secrets
  namespace: production
  labels:
    app: droid
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: droid-gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: droid-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      mergePolicy: Merge
      metadata:
        labels:
          app: droid
      data:
        _DROID_STARTUP_HOOK_GROUP: "droid_deploy.init"
        _DROID_STARTUP_HOOK_PACKAGE: "droid-deploy"
  data:
  - secretKey: LIVEKIT_SIP_URI
    remoteRef:
      key: LIVEKIT_SIP_URI
  - secretKey: LIVEKIT_URL
    remoteRef:
      key: LIVEKIT_URL
  - secretKey: LIVEKIT_API_KEY
    remoteRef:
      key: LIVEKIT_API_KEY
  - secretKey: LIVEKIT_API_SECRET
    remoteRef:
      key: LIVEKIT_API_SECRET
  - secretKey: DEEPGRAM_API_KEY
    remoteRef:
      key: DEEPGRAM_API_KEY
  - secretKey: CARTESIA_API_KEY
    remoteRef:
      key: CARTESIA_API_KEY
  - secretKey: ELEVEN_API_KEY
    remoteRef:
      key: ELEVEN_API_KEY
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: OPENAI_API_KEY
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: ANTHROPIC_API_KEY
  - secretKey: DEEPSEEK_API_KEY
    remoteRef:
      key: DEEPSEEK_API_KEY
  - secretKey: ANTICAPTCHA_KEY
    remoteRef:
      key: ANTICAPTCHA_KEY
  - secretKey: TAVILY_API_KEY
    remoteRef:
      key: TAVILY_API_KEY
  - secretKey: ORCHESTRA_ADMIN_KEY
    remoteRef:
      key: ORCHESTRA_ADMIN_KEY
  - secretKey: VERTEXAI_CREDENTIALS
    remoteRef:
      key: VERTEXAI_CREDENTIALS
  - secretKey: SHARED_UNIFY_KEY
    remoteRef:
      key: SHARED_UNIFY_KEY
