steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'trigger-comms-app-build'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -euo pipefail
    gcloud builds triggers run unity-comms-app-staging-unity-deploy \
      --project=${PROJECT_ID} \
      --region=${_REGION} \
      --branch=staging

options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: 'us-central1'

timeout: '600s'
