---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unity-pipeline-worker
  namespace: staging
  labels:
    app: unity-pipeline-worker
    component: pipeline-worker
    environment: staging
  annotations:
    iam.gke.io/gcp-service-account: service-account@example.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unity-pipeline-worker
  namespace: production
  labels:
    app: unity-pipeline-worker
    component: pipeline-worker
    environment: production
  annotations:
    iam.gke.io/gcp-service-account: service-account@example.iam.gserviceaccount.com
