name: Build and Deploy to Cloud Run

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'mail_watch/**'

env:
  SERVICE_NAME: unity-comms-app
  AR_NAME: unity-comms-app-repo
  IMAGE_NAME: unity-comms-app-image
  REGION: us-central1
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Auth into Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ env.GCP_PROJECT }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${{ secrets.SA_EMAIL }} \
          --update-secrets=GCP_SA_KEY=gcp-sa-key:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,TWILIO_API_SID=TWILIO_API_SID:latest,TWILIO_API_SECRET=TWILIO_API_SECRET:latest,TWIML_SIP_USERNAME=TWIML_SIP_USERNAME:latest,TWIML_SIP_PASSWORD=TWIML_SIP_PASSWORD:latest,LIVEKIT_URL=LIVEKIT_URL:latest,LIVEKIT_API_KEY=LIVEKIT_API_KEY:latest,LIVEKIT_API_SECRET=LIVEKIT_API_SECRET:latest,LIVEKIT_SIP_URI=LIVEKIT_SIP_URI:latest,UNIFY_KEY=UNIFY_KEY:latest,UNIFY_COMMS_URL=UNIFY_COMMS_URL:latest