on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Auth into Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install black
      run: pip install black

    - name: Run black check
      run: black --diff --color --check .

  adapter_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Auth into Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up Environment
      run: |
        pip install -r requirements.txt
        pip install -r adapters/requirements.txt

    - name: Run adapter tests
      run: pytest tests/test_adapters.py
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        LIVEKIT_SIP_URI: ${{ secrets.LIVEKIT_SIP_URI }}
        LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
        LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
        LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        ORCHESTRA_ADMIN_KEY: ${{ secrets.ORCHESTRA_ADMIN_KEY }}
        STAGING: true
        PROJECT_ID: gcp-project-runtime
